default:
  image: Debian 8
  flavor: vps-ssd-1
  network: Ext-Net

servers:
  manager:
    flavor: vps-ssd-2
    meta:
      docker: manager

  worker:
    instances-nb: 2
    meta:
      docker: worker
